### ISSUE TITLE
buffer overrun i=xx;endindex=xx;writeindex=xxx.

### ISSUE THREAD

**Issue by wang3156** [svn2github/npoi#14]
Following is the problem:
I used version NPOI 2.1.1 with c# （C sharp）.
I uploaded an excel with Microsoft excel 2003 on client. I opened the create custom settings with NPOI on the server and use “write” of hssfworkbook into filestream. However, an error occurred- buffer overrun i=xx;endindex=xx;writeindex=xxx. ( Excel was 10 columns 20 rows , which only added a filter function.)

**Comment by ooropuloo** [comment]
Hi, Any update? I got the same problem
In my case, i found "remove the excel filter in sheet" can fix this problem...
Seems it caused by hidden rows...

**Comment by ooropuloo** [comment]
> Hi, Any update? I got the same problem

In my case, i found "remove the excel filter in sheet" can fix this problem...
