### ISSUE TITLE
IWorkbook.Write(stream)

### ISSUE THREAD

**Issue by ssquirrel** [svn2github/npoi#19]
hello,
I am currently using NPOI in my project and I encounter this very weird situation when try to write IWorkbook to file. The write function seems buggy to me. When you do:
```
var workbook =  WorkbookFactory.Create("template.xlsx"); //open an existing excel file
 //do editing with the workbook
workbook.write(new FileStream("test.xlsx", FileMode.Create))
workbook.close()
```
Both original file and the new file will be updated. However if you comment out the write() call, nothing would happen. So my question is how am I supposed to update an existing file or save changes to another file only(keeping original file intact)? 

many thanks in advance!

**Comment by ssquirrel** [comment]
It appears that if the underlying type is `HSSFWorkbook` then there is no problem as the constructor of `HSSFWorkbook` would close the file stream after construction allowing you to open the stream again to overwrite its content. But that is not the case with `XSSFWorkbook`. `XSSFWorkbook` keeps the file stream open until `Close()`. Subsequent access can only be made read only. Hence it exhibited problem i described above. Either you get a duplicate or nothing.

**Comment by ssquirrel** [comment]
OK. just worked out a solution. if you open .xlsx file by using `WorkbookFactory.Create(stream)`, the stream would be properly closed so you may open it again to overwrite it.

**Comment by tonyqus** [comment]
hello, this repo is for synchonization from svn to github only. Please go to https://github.com/tonyqus/npoi/issues to create your issue.
