### ISSUE TITLE
Fix the BUG that XSSF writes to  memoryStream

### ISSUE THREAD

**Issue by wekingc** [svn2github/npoi#7]
When we use XSSF writes to memoryStream, memoryStream will be closed. So we can NOT download xlsx file from web.

**Comment by rpmansion** [comment]
for now you can do a work around with that by doing the following codes:
`workbook.write(ms);`
`var buffer = ms.ToArray();`
`var bufferLength = buffer.Length;`

**Comment by wekingc** [comment]
XSSFWorkboo book = New NPOI.XSSF.UserModel.XSSFWorkbook();
book.Write(Response.OutputStream);
book =null;
Response.Flush();
Response.End();

With these codes, I can fix that problem.
